export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const REMOVE_USER_DATA = "REMOVE_USER_DATA";
export const USER_DETAILS_LOCAL_STORAGE = "USER_DETAILS_LOCAL_STORAGE";
